### ISSUE TITLE
Core Dumped

### ISSUE THREAD

**Issue by SionBayliss** [johnlees/unitig-caller#8] opened 2021-04-09 13:22 UTC
Hi John, 

I am getting an 'Illegal instruction (core dumped)' error on a fresh install of unitig-caller under conda 4.9.2 (python3). I confirmed on a CLIMB instance. I have a working environment from an older conda version.

All the best,
Sion

**Comment by johnlees** [comment] 2021-04-12 10:34
This is a slightly tricky one, and could be caused by a CPU incompatibility, environment issue, or it may be a bug in our code.

What version of unitig-caller is this with, and does an older version work? What was the command used?

If you clone this repo and run:
```
python setup.py install
```
in your conda environment, does that fix the issue?

**Comment by SionBayliss** [comment] 2021-04-12 11:23
Hi John, 

Version 1.1.0 works on both systems. The issue with version 1.2 maybe incompatibility between seqan3 and my gcc/c++ compiler in both distances (<C++17). It doesn't look to be remedied by installing gcc/c++ through conda alone (conda install gcc_linux-64 gxx_linux-64) as it still core dumps and fails to install via 'python setup.py install' with the following message:

'''
CMake Error at /home/sbayliss/miniconda3/envs/test_unitigs/share/cmake/seqan3/seqan3-config.cmake:114 (message):
  SeqAn3 requires C++17, but your compiler does not support it.
Call Stack (most recent call first):
  /home/sbayliss/miniconda3/envs/test_unitigs/share/cmake/seqan3/seqan3-config.cmake:237 (seqan3_config_error)
  CMakeLists.txt:40 (find_package)
'''

This maybe due to conda installing gcc and c++ binaries with non-standard names (e.g. x86_64-conda-linux-gnu-cpp for c++). Sorry I don't have time to debug further :)

All the best,
Sion

**Comment by johnlees** [comment] 2021-06-22 16:04
@SionBayliss I *think* we have fixed this in the most recent bioconda package (and 2a3da00bf67e8d503f2c0de6745caf7ab644bd4d), if you want to try updating (should have a build ending _2, but the same version number 1.2.0)

**Comment by ylz0** [comment] 2021-06-24 03:49
@johnlees @SionBayliss  Following these instructions and then doing a conda install helped me:
Please install CentOS SCL repository:

yum install centos-release-scl
Install C++ support for GCC version 7:

yum install devtoolset-7-gcc-c++ --enablerepo='centos-sclo-rh'
Switch enviroment to this compiler before build:

scl enable devtoolset-7 'bash'

**Comment by johnlees** [comment] 2021-07-09 13:29
Going to close this for now, but please reopen if still an issue

**Closed as completed by johnlees** 2021-07-09 13:29 UTC
