### ISSUE TITLE
Bug - incorrect file names not being reported to user

### ISSUE THREAD

**Issue by SionBayliss** [johnlees/unitig-caller#5] opened 2020-10-06 10:37 UTC
Hi John, 

Only a minor bug I found when not following your detailed README closely enough. 

If the files are not specified as 'reads.txt' or 'refs.txt' then the return statements at line 93 of bifrost.py doesn't interrupt the script and print the error message. It gives a file not found *.gfa error instead. 

```
 else:
        return "Please submit input files as 'reads.txt' or 'refs.txt' only"
```

All the best,
Sion

**Comment by johnlees** [comment] 2020-10-06 11:34
Duplicate of #6, closing and responding there

**Closed as completed by johnlees** 2020-10-06 11:34 UTC
